# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "cloudflare/cloudflared:2024.11.0-arm64"
  amd64: "cloudflare/cloudflared:2024.11.0-amd64"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Cloudflare Tunnel client"
  org.opencontainers.image.description: "Client for Cloudflare Tunnel, a tunneling daemon that proxies traffic from the Cloudflare network to your origins."
  org.opencontainers.image.source: "https://github.com/fredericks1982/hass-addon-cloudflared"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
