# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Cloudflare Tunnel client
version: "2024.10.0"
slug: cloudflared
description: Client for Cloudflare Tunnel, a tunneling daemon that proxies traffic from the Cloudflare network to your origins.
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: "https://github.com/fredericks1982/hass-addon-cloudflared"
startup: system
host_network: true
init: false
#map:
#  - share:rw
options:
  token: ""
schema:
  token: "str"
#image: "ghcr.io/home-assistant/{arch}-addon-example"
panel_icon: mdi:router-network